# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('member_password', models.CharField(max_length=50)),
                ('member_address', models.CharField(max_length=200)),
                ('member_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
